In [2]:
%gui qt

In [3]:
from mayavi import mlab

In [4]:
import numpy as np

In [5]:
mlab.test_contour3d()

In [6]:
mlab.clf()

In [7]:
position_data = [
    [1,1,1],
    [2,2,2],
    [3,3,3],
    [4,4,4],
]


In [49]:
from object import R
R = 1
frame_x, frame_y, frame_z = np.mgrid[-10*R: 10*R: 2j,-10*R: 10*R: 2j,-10*R: 10*R: 2j]

# print(frame_x)

mlab.clf()
mlab.points3d(frame_x, frame_y, frame_z, opacity=0)



In [54]:

from object import object, R, M
import numpy as np
import time


# if __name__ == "__main__":

'''
options
Display while simulation being run ? ---- can show the difference 
in simulation speeds of differetn optimizations
Display after simulation done for limited time.. Can Either do it in 
a fixed simulation time, or real time

scale ?   
No of objects ?
Size of interval simulations ?

What to simulate ? Simulate the questions for which answers are solved by 
simulations... :) 


'''
x, y, z = 2*R, 2*R, 0
vx, vy, vz = 0, 0, 4000

# frame_ref_x = [10*R, 10*R, ]
# frame_ref_y = [10*R,]
# frame_ref_z = [10*R,]


ob = object(x=x, y=y, z=z, vx=vx, vy=vy, vz=vz)
earth = object(m=M)

T = 365*24*3600    # The time to simulate in seconds ?
N = int(T/150)       # No of frames

dt = T/N

frames = np.zeros((N, 3))

t1 = time.perf_counter()
mlab.clf()


# OUTSCALING WITH 1e6 the whole system

x_points = [
earth.x/1e6,
ob.x/1e6,
]

y_points = [
earth.y/1e6,
ob.y/1e6,
]

z_points = [
earth.z/1e6,
ob.z/1e6,
]

scalars_need=[
    1.8,
    0.8, 
]

mlab.clf()
# earth_graphic = mlab.points3d(earth.x/1e6, earth.y/1e6, earth.z/1e6, 0.3, scale_factor = 1)
# satellite_graphic = mlab.points3d(ob.x/1e6, ob.y/1e6, ob.z/1e6, 0.8, scale_factor=1)

mlab.points3d(frame_x, frame_y, frame_z, opacity = 0)

# todo: check reference frame viewing...


planet_satellite_graphic = mlab.points3d(x_points, y_points, z_points, scalars_need, 
                                         scale_factor=1)
# planet_satellite_graphic = mlab.points3d(x_points, y_points, z_points)

# earth_graphic.glyph.glyph.clamping = False
# satellite_graphic.glyph.glyph.clamping = False

print(N)



210240


In [132]:
mlab.clf()
# mlab.points3d(frame_x.flatten(), frame_y.flatten(), frame_z.flatten())
# print(frame_x)
mlab.points3d([0], [0], [0])
mlab.points3d([5000], [0], [0])


In [139]:
mlab.points3d(frame_x, frame_y, frame_z, np.zeros_like(frame_x))
mlab.points3d(0, 0, 0)

print(frame_x)

[[[-10. -10.]
  [-10. -10.]]

 [[ 10.  10.]
  [ 10.  10.]]]


In [52]:

planet_satellite_graphic = mlab.points3d(x_points, y_points, z_points, scalars_need, 
                                         scale_factor=1)

In [55]:

ctr = 0
# @mlab.animate(delay=100)
delay = 00
def anim():
    for i in range(200) :
        # ctr += 1
        ob.update_due_ob(dt, earth)
        frames[i, :] = ob.give_pos()
        planet_satellite_graphic.mlab_source.x = [earth.x/1e6, ob.x/1e6]
        planet_satellite_graphic.mlab_source.y = [earth.y/1e6, ob.y/1e6]
        planet_satellite_graphic.mlab_source.z = [earth.z/1e6, ob.z/1e6]
        mlab.process_ui_events()
        print(f"animation-{i} \t done")
        print([earth.x/1e6, ob.x/1e6])
        print([earth.y/1e6, ob.y/1e6])
        print([earth.z/1e6, ob.z/1e6])
        # yield
        mlab.process_ui_events()
        mlab.savefig(f'./pics/anim_{i}.png')


        time.sleep(delay/1000)
        

anim()
print(ctr)
t2 = time.perf_counter()

print("Time taken to compute: ", t2-t1)

    

animation-0 	 done
[0.0, 12.736532567903847]
[0.0, 12.736532567903847]
[0.0, 0.6]
animation-1 	 done
[0.0, 12.697570603356155]
[0.0, 12.697570603356155]
[0.0, 1.1990816402024207]
animation-2 	 done
[0.0, 12.639092308036123]
[0.0, 12.639092308036123]
[0.0, 1.7963202763653883]
animation-3 	 done
[0.0, 12.561081433442943]
[0.0, 12.561081433442943]
[0.0, 2.3907828612627307]
animation-4 	 done
[0.0, 12.463527636894213]
[0.0, 12.463527636894213]
[0.0, 2.9815257916766686]
animation-5 	 done
[0.0, 12.34642695166073]
[0.0, 12.34642695166073]
[0.0, 3.5675927142653325]
animation-6 	 done
[0.0, 12.2097823787989]
[0.0, 12.2097823787989]
[0.0, 4.148012283868043]
animation-7 	 done
[0.0, 12.053604610007097]
[0.0, 12.053604610007097]
[0.0, 4.72179586814792]
animation-8 	 done
[0.0, 11.877912892751882]
[0.0, 11.877912892751882]
[0.0, 5.287935192954634]
animation-9 	 done
[0.0, 11.682736051013114]
[0.0, 11.682736051013114]
[0.0, 5.845399923459636]
animation-10 	 done
[0.0, 11.468113677314683]
[0.0, 11.4

In [66]:
print(frames.shape)
# print(R)
print(frames[:200, :]/(R))

(210240, 3)
[[ 1.99694772  1.99694772  0.09407338]
 [ 1.99083892  1.99083892  0.18800277]
 [ 1.98167016  1.98167016  0.28164319]
 [ 1.96943892  1.96943892  0.37484836]
 [ 1.95414356  1.95414356  0.46747033]
 [ 1.93578347  1.93578347  0.55935916]
 [ 1.91435911  1.91435911  0.65036254]
 [ 1.88987216  1.88987216  0.74032547]
 [ 1.86232563  1.86232563  0.82908987]
 [ 1.83172406  1.83172406  0.91649419]
 [ 1.79807364  1.79807364  1.00237303]
 [ 1.76138249  1.76138249  1.08655675]
 [ 1.72166087  1.72166087  1.16887105]
 [ 1.6789215   1.6789215   1.24913653]
 [ 1.63317985  1.63317985  1.32716828]
 [ 1.58445454  1.58445454  1.40277543]
 [ 1.53276775  1.53276775  1.47576068]
 [ 1.47814574  1.47814574  1.54591986]
 [ 1.42061932  1.42061932  1.61304147]
 [ 1.36022458  1.36022458  1.67690625]
 [ 1.2970035   1.2970035   1.73728666]
 [ 1.23100479  1.23100479  1.79394656]
 [ 1.1622848   1.1622848   1.84664071]
 [ 1.0909085   1.0909085   1.89511452]
 [ 1.01695066  1.01695066  1.93910371]
 [ 0.94049711

In [ ]:
""" Tutorial for animation """
# %load solutions/03_wave_anim.py
import time
for i in range(25):
    s.mlab_source.scalars = np.sin((x*x + y*y) + 8*np.pi*i/25)
    mlab.process_ui_events()
    mlab.savefig('/tmp/anim_%03d.png')
    # print('/tmp/anim_%03d.png')
    time.sleep(0.05)

# savefig into /tmp is a jugaad
# WORKING!

In [28]:
satellite_graphic = mlab.points3d(ob.x/1e6, ob.y/1e6, ob.z/1e6)
# satellite_graphic = mlab.points3d(10000000, 10000000, 10000000)
""" 
Scaling with 1e6 
"""
ob.x, ob.y, ob.z/1e6

(12756000.0, 12756000.0, 12.756)

In [1]:
# s = mlab.surf(x, y, np.asarray(x*0.1, 'd'))

mlab.clf()
# x,y = np.mgrid[0:3:1, 0:3:1 ]
x, y, z = [0,0,0]
s = mlab.points3d(x,y,z)
mlab.points3d(x+10,y+10,z+10)


@mlab.animate(delay=10, ui=False)
def anim():
    for t in np.linspace(0, 9,100):
        # s.mlab_source.scalars = np.asarray(x*0.1*(i+1), 'd')
        s.mlab_source.x = t
        s.mlab_source.y = t
        s.mlab_source.z = t
        print("AKASH")
        yield

anim()

NameError: name 'mlab' is not defined

In [8]:
mlab.clf()
R = 6.378e6

data = np.load("data_visual.npy")
data = data/R

print(data.shape)
print(data[:100])




(210240, 3)
[[ 1.99694772  1.99694772  0.09407338]
 [ 1.99083892  1.99083892  0.18800277]
 [ 1.98167016  1.98167016  0.28164319]
 [ 1.96943892  1.96943892  0.37484836]
 [ 1.95414356  1.95414356  0.46747033]
 [ 1.93578347  1.93578347  0.55935916]
 [ 1.91435911  1.91435911  0.65036254]
 [ 1.88987216  1.88987216  0.74032547]
 [ 1.86232563  1.86232563  0.82908987]
 [ 1.83172406  1.83172406  0.91649419]
 [ 1.79807364  1.79807364  1.00237303]
 [ 1.76138249  1.76138249  1.08655675]
 [ 1.72166087  1.72166087  1.16887105]
 [ 1.6789215   1.6789215   1.24913653]
 [ 1.63317985  1.63317985  1.32716828]
 [ 1.58445454  1.58445454  1.40277543]
 [ 1.53276775  1.53276775  1.47576068]
 [ 1.47814574  1.47814574  1.54591986]
 [ 1.42061932  1.42061932  1.61304147]
 [ 1.36022458  1.36022458  1.67690625]
 [ 1.2970035   1.2970035   1.73728666]
 [ 1.23100479  1.23100479  1.79394656]
 [ 1.1622848   1.1622848   1.84664071]
 [ 1.0909085   1.0909085   1.89511452]
 [ 1.01695066  1.01695066  1.93910371]
 [ 0.94049711

In [43]:
R = 6.378e8

mlab.clf()
earth_obj = mlab.points3d(
    [0],[0],[0],color=(1,0,0)
)

sat_init_pos = (data[0])

sat_obj = mlab.points3d(
    [sat_init_pos[0]],
    [sat_init_pos[1]],
    [sat_init_pos[2]],
    color=(0.5, 0.5, 0.5)
) 

print(sat_init_pos)

[1. 1. 0.]


In [36]:
import time

In [44]:

ctr = 0

delay = 00
def anim(mobj, posval):
    for i in range(200) :
        # ctr += 1

        mobj.mlab_source.x = posval[i][0]
        mobj.mlab_source.y = posval[i][1]
        mobj.mlab_source.z = posval[i][2]

        mlab.process_ui_events()
        print(f"animation-{i} \t done")
        # print([earth.x/1e6, ob.x/1e6])
        # print([earth.y/1e6, ob.y/1e6])
        # print([earth.z/1e6, ob.z/1e6])
        # yield
        mlab.process_ui_events()
        mlab.savefig(f'./pics/anim_{i}.png')

        time.sleep(delay/1000)
        
t1 = time.perf_counter()
anim(sat_obj, data)
print(ctr)
t2 = time.perf_counter()

print("Time taken to compute: ", t2-t1)


animation-0 	 done
animation-1 	 done
animation-2 	 done
animation-3 	 done
animation-4 	 done
animation-5 	 done
animation-6 	 done
animation-7 	 done
animation-8 	 done
animation-9 	 done
animation-10 	 done
animation-11 	 done
animation-12 	 done
animation-13 	 done
animation-14 	 done
animation-15 	 done
animation-16 	 done
animation-17 	 done
animation-18 	 done
animation-19 	 done
animation-20 	 done
animation-21 	 done
animation-22 	 done
animation-23 	 done
animation-24 	 done
animation-25 	 done
animation-26 	 done
animation-27 	 done
animation-28 	 done
animation-29 	 done
animation-30 	 done
animation-31 	 done
animation-32 	 done
animation-33 	 done
animation-34 	 done
animation-35 	 done
animation-36 	 done
animation-37 	 done
animation-38 	 done
animation-39 	 done
animation-40 	 done
animation-41 	 done
animation-42 	 done
animation-43 	 done
animation-44 	 done
animation-45 	 done
animation-46 	 done
animation-47 	 done
animation-48 	 done
animation-49 	 done
animation-