In [1]:
%gui qt
from mayavi import mlab
import numpy as np
import time

In [3]:
# for testing
mlab.test_contour3d_anim()

In [104]:
# DATA_SCALE_FACTOR = radius_earth
DATA_SCALE_FACTOR = 6.378e6

# Lets divide everything by R, to get intution
data = np.load("data_visual.npy")
data = data/DATA_SCALE_FACTOR

print(data.shape)
print(data[:100])

(210240, 3)
[[ 1.99694772  1.99694772  0.09407338]
 [ 1.99083892  1.99083892  0.18800277]
 [ 1.98167016  1.98167016  0.28164319]
 [ 1.96943892  1.96943892  0.37484836]
 [ 1.95414356  1.95414356  0.46747033]
 [ 1.93578347  1.93578347  0.55935916]
 [ 1.91435911  1.91435911  0.65036254]
 [ 1.88987216  1.88987216  0.74032547]
 [ 1.86232563  1.86232563  0.82908987]
 [ 1.83172406  1.83172406  0.91649419]
 [ 1.79807364  1.79807364  1.00237303]
 [ 1.76138249  1.76138249  1.08655675]
 [ 1.72166087  1.72166087  1.16887105]
 [ 1.6789215   1.6789215   1.24913653]
 [ 1.63317985  1.63317985  1.32716828]
 [ 1.58445454  1.58445454  1.40277543]
 [ 1.53276775  1.53276775  1.47576068]
 [ 1.47814574  1.47814574  1.54591986]
 [ 1.42061932  1.42061932  1.61304147]
 [ 1.36022458  1.36022458  1.67690625]
 [ 1.2970035   1.2970035   1.73728666]
 [ 1.23100479  1.23100479  1.79394656]
 [ 1.1622848   1.1622848   1.84664071]
 [ 1.0909085   1.0909085   1.89511452]
 [ 1.01695066  1.01695066  1.93910371]
 [ 0.94049711

In [105]:
# Frame of reference setup
frame_x, frame_y, frame_z = np.mgrid[-10: 10: 2j,-10: 10: 2j,-10: 10: 2j]

mlab.clf()

# Uncomment the below line to make endpoints invisible
# mlab.points3d(frame_x, frame_y, frame_z, opacity=0)
mlab.points3d(frame_x, frame_y, frame_z, opacity=1)


In [108]:

VISUAL_SCALE_FACTOR = 3

In [106]:
earth_obj = mlab.points3d(0,0,0, color = (1,0,0))

sat_init_pos = data[0] * VISUAL_SCALE_FACTOR

sat_obj = mlab.points3d(
        sat_init_pos[0],
        sat_init_pos[1],
        sat_init_pos[2],
        color = (0.5, 0.5, 0.5)
    )

print(sat_init_pos)

sat_traj = mlab.plot3d(
    sat_init_pos[0],
    sat_init_pos[1],
    sat_init_pos[2],
)



[5.99084316 5.99084316 0.28222013]


In [107]:
# Lets once try mlab animate decorator...
# If it doesn't work, do with save_fig and delay and all
# @mlab.animate

# Not using decorator here, as I need inputs to this function...
num_frames_interest = 150

def anim(moving_obj, data, num_frames = 50, obj_traj = None, pics_folder_name = None):

    # decorator not working... Animation stops in between
    # Now again,it doesn't stop

    delay = 100

    # @mlab.animate(delay = 100)

    for i in range(num_frames):
        moving_obj.mlab_source.x = data[i][0] * VISUAL_SCALE_FACTOR  
        moving_obj.mlab_source.y = data[i][1] * VISUAL_SCALE_FACTOR 
        moving_obj.mlab_source.z = data[i][2] * VISUAL_SCALE_FACTOR 

        # Trajectory is not working, bodies just dont animate ...

        if obj_traj is not None:
            obj_traj.mlab_source.reset(
                x = data[:i+1, 0] * VISUAL_SCALE_FACTOR,
                y = data[:i+1, 1] * VISUAL_SCALE_FACTOR,
                z = data[:i+1, 2] * VISUAL_SCALE_FACTOR
            )

        # Uncomment below line, if using decorator
        # yield
        # uncomment below lines, if not using decorator
        mlab.process_ui_events()
        # This savefig is a cruel trick to re-create the image or smthing like that
        if pics_folder_name is None:
            mlab.savefig(f'./pics/anim_{i}.png')
        else:
            mlab.savefig(f'/{pics_folder_name}/anim_{i}.png')

        # time.sleep(delay/1000)


anim(sat_obj, data, num_frames=num_frames_interest, obj_traj=sat_traj )


# Obtained good animation results! Creates a folder with pic names for the same